version: '3.7'

services:
  quiz-service:
    build: quizservice/.
    container_name: quizservice
    ports:
      - "8090:8090"
    depends_on:
      - quiz-db
    networks:
      - app-net

  quiz-db:
    container_name: quiz-db
    image: mongo
    volumes:
      - /tmp/database/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - app-net

  user-service:
    build: userservice/.
    container_name: userservice
    ports:
      - "8091:8091"
    networks:
      - app-net

  user-db:
    container_name: user-db
    image: mysql
    environment:
      - MYSQL_DATABASE=user-db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /tmp/database/mysql:/data
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-net

networks:
  app-net:
    name: nat