server:
  port: 8091
  servlet:
    context-path: /api/users
#
#jetty:
#  threadPool:
#    maxThreads: 10
#    minThreads: 10
#
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/user-db?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: mohit
    password: mohit
    driverClassName: com.mysql.cj.jdbc.Driver
  #    validation-query: select 1;
  #    maxActive: 100
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect