server:
  port: 8091
  servlet:
    context-path: /api/users


eventstarter:
  enabled: true
  listener:
    enabled-events:
      - foo
#
#jetty:
#  threadPool:
#    maxThreads: 10
#    minThreads: 10
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-db?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: mohit
    password: mohit
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: quizServiceGroup