server:
  port: 8090
  servlet:
    context-path: /api/quizzes


#jetty:
#  threadPool:
#    maxThreads: 10
#    minThreads: 10
#


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: quizServiceGroup


bootstrap:
  servers: localhost:9092
key:
  serializer: org.apache.kafka.common.serialization.StringSerializer
  deserializer: org.apache.kafka.common.serialization.StringDeserializer
value:
  serializer: org.apache.kafka.common.serialization.StringSerializer
  deserializer: org.apache.kafka.common.serialization.StringDeserializer
