server:
  port: 8090
  servlet:
    context-path: /api/quizzes
#
#jetty:
#  threadPool:
#    maxThreads: 10
#    minThreads: 10
#
spring:
  data:
    mongodb:
      host: quiz-db
      port: 27017

#    username: mohit
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#    validation-query: select 1;
#    maxActive: 100
#  jpa:
#    show-sql: false
#    generate-ddl: false
#    properties:
#      hibernate:
#        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        dialect: org.hibernate.dialect.MySQLDialect
#        hbm2ddl.auto: validate